# Generated by Django 5.2 on 2025-04-14 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('user_password', models.CharField(max_length=128)),
                ('is_manager', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'admins',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_type', models.CharField(blank=True, max_length=50, null=True)),
                ('car_color', models.CharField(blank=True, max_length=50, null=True)),
                ('car_name', models.CharField(blank=True, max_length=50, null=True)),
                ('car_state', models.CharField(blank=True, max_length=50, null=True)),
                ('car_metric', models.IntegerField(blank=True, null=True)),
                ('SellingPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('PurchasePrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('SellingDateTime', models.DateField(blank=True, null=True)),
                ('PurchaseDateTime', models.DateField(blank=True, null=True)),
                ('chassis', models.CharField(max_length=17, unique=True)),
            ],
            options={
                'db_table': 'car',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('profits', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('car', models.ForeignKey(blank=True, db_column='car_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='companyFrontend.car')),
            ],
            options={
                'db_table': 'financial',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('car', models.ForeignKey(blank=True, db_column='car_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='companyFrontend.car')),
            ],
            options={
                'db_table': 'inventory',
                'managed': True,
            },
        ),
    ]
