# Generated by Django 5.2 on 2025-05-15 03:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyFrontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year_manufacture',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
